# -*- coding: utf-8 -*-
"""ssd object detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wzjLYKY1Lkc_FwJNipOUZIbd8ypXe83-
"""

import numpy as np
import cv2

cam = cv2.VideoCapture(0)
cam.set(cv2.CAP_PROP_FPS, 7)

im_path = "C:\\Users\\TheTa\\Downloads\\opencv_object_detection\\000456.jpg"
config_path = "/home/pi/raspberry-pi-opencv/yolov3-tiny.cfg"
weights_path = "/home/pi/raspberry-pi-opencv/yolov3-tiny.weights"
min_prob = 0.2

CLASSES = open('/home/pi/raspberry-pi-opencv/coco.names').read().strip().split('\n')

net = cv2.dnn.readNetFromDarknet(config_path, weights_path)
while True:
    ret, image = cam.read()
    (h, w) = image.shape[:2]
    blob = cv2.dnn.blobFromImage(image, 1 / 255.0, (192, 192), swapRB=True, crop=False)
    net.setInput(blob)
    detections = net.forward()
    
    boxes = []
    confidences = []
    classIDs = []
    
    for output in detections:
        scores = output[5:]
        classID = np.argmax(scores)
        confidence = scores[classID]
        if confidence > 0.2:
            box = output[0:4] * np.array([w, h, w, h])
            (centerX, centerY, width, height) = box.astype("int")
            x = int(centerX - (width / 2))
            y = int(centerY - (height / 2))
            boxes.append([x, y, int(width), int(height)])
            confidences.append(float(confidence))
            classIDs.append(classID)
    idxs = cv2.dnn.NMSBoxes(boxes, confidences, 0.2, 0.3)
    if len(idxs) > 0:
        for i in idxs.flatten():
            (x, y) = (boxes[i][0], boxes[i][1])
            (w, h) = (boxes[i][2], boxes[i][3])
            cv2.rectangle(image, (x, y), (x + w, y + h), (0, 250, 180), 2)
            text = "{}: {:.4f}".format(CLASSES[classIDs[i]], confidences[i])
            cv2.putText(image, text, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 250, 180), 2)

    cv2.imshow("Output", image)
    cv2.waitKey(1)


