# -*- coding: utf-8 -*-
"""ssd object detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wzjLYKY1Lkc_FwJNipOUZIbd8ypXe83-
"""

import numpy as np
#import argparse
import cv2
#import matplotlib.pyplot as plt

cam = cv2.VideoCapture(0)
cam.set(cv2.CAP_PROP_FPS, 30)
#cam.set(cv2.CAP_PROP_FRAME_WIDTH, 1300)
#cam.set(cv2.CAP_PROP_FRAME_HEIGHT, 1500)

# im_path = "/content/000067.jpg"
im_path = "C:\\Users\\TheTa\\Downloads\\opencv_object_detection\\000456.jpg"
# protxt_path = "/content/deploy.prototxt"
protxt_path = "/home/ubuntu/raspberry-pi-opencv/deploy.prototxt"
model_path = "/home/ubuntu/raspberry-pi-opencv/mobilenet_iter_73000.caffemodel"
min_prob = 0.2

CLASSES = ["background", "aeroplane", "bicycle", "bird", "boat",
	"bottle", "bus", "car", "cat", "chair", "cow", "diningtable",
	"dog", "horse", "motorbike", "person", "pottedplant", "sheep",
	"sofa", "train", "tvmonitor"]

net = cv2.dnn.readNetFromCaffe(protxt_path, model_path)

while True:
	ret, image = cam.read()
	# image = cv2.imread(im_path)
	(h, w) = image.shape[:2]
	blob = cv2.dnn.blobFromImage(cv2.resize(image, (300, 300)), 0.007843, (300, 300), 127.5)

	net.setInput(blob)
	detections = net.forward()

	for i in np.arange(0, detections.shape[2]):
		confidence = detections[0, 0, i, 2]
		if confidence > min_prob:
			idx = int(detections[0, 0, i, 1])
			box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
			(startX, startY, endX, endY) = box.astype("int")
			label = "{}: {:.2f}%".format(CLASSES[idx], confidence * 100)
			cv2.rectangle(image, (startX, startY), (endX, endY), (0, 180, 255), 2)
			y = startY - 15 if startY - 15 > 15 else startY + 15
			cv2.putText(image, label, (startX, y), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 180, 255), 2)

	cv2.imshow("Output", image)
	# plt.imshow(image)
	cv2.waitKey(1)
